name: Create GitHub App Installation Token
author: jon wong <j@jnwng.com>
description: A GitHub Action to retrieve a GitHub App's installation access token, making it easy to compose GitHub Actions workflows.
branding:
  color: green
  icon: link
inputs:
  appId:
    description: The GitHub App ID
    required: true
  installationId:
    description: The GitHub App installation ID
    required: true
  privateKey:
    description: The private key used to sign the JWT
    required: true
  baseUrl:
    description: Optional base url for github requests
    required: false
outputs:
  token:
    description: The generated RS256-signed JWT
runs:
  using: "node12"
  main: "dist/index.js"
