name: Step One
on:
  check_run:
    types: [created]

jobs:
  stepOne:
    name: The first job in a complex workflow.
    runs-on: ubuntu-latest
    if: github.event.check_run.name == 'Step One'
    steps:
      - uses: actions/checkout@master
      - uses: ./
        id: installationToken
        with: 
          appId: 72750
          installationId: 10503340
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      # This is where the magic begins — the "completion" of this check will trigger
      # the `example-workflow-step-two` GitHub Actions workflow.
      # Critically, though, _any_ part of your system can create and complete these check_runs, including GitHub Actions themselves.
      - uses: actions/github-script@v2
        with:
          github-token: ${{ steps.installationToken.outputs.token }}
          script: |
            await github.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: "${{ github.event.check_run.id }}",
              status: "completed",
              conclusion: "success"
            })
